CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ApprovalDecisions" (
    "Id" uuid NOT NULL,
    "TransactionId" uuid NOT NULL,
    "AnalystId" uuid NOT NULL,
    "Decision" character varying(50) NOT NULL,
    "ApprovalLevel" integer NOT NULL,
    "Notes" text,
    "DecidedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ApprovalDecisions" PRIMARY KEY ("Id")
);

CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Action" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "IpAddress" text NOT NULL,
    "Details" text NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "DeviceSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "DeviceFingerprint" text NOT NULL,
    "IpAddress" text NOT NULL,
    "Status" text NOT NULL,
    "LastLoginAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DeviceSessions" PRIMARY KEY ("Id")
);

CREATE TABLE "FraudFlags" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TransactionId" integer NOT NULL,
    "RiskScore" integer NOT NULL,
    "Reasons" text NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FraudFlags" PRIMARY KEY ("Id")
);

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Recipient" text NOT NULL,
    "RecipientName" text NOT NULL,
    "Type" text NOT NULL,
    "Message" text NOT NULL,
    "DeliveryStatus" text NOT NULL,
    "ChannelDetails" text NOT NULL,
    "LatencyMs" integer NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

CREATE TABLE "ReviewQueues" (
    "Id" uuid NOT NULL,
    "TransactionId" uuid NOT NULL,
    "QueueCode" text NOT NULL,
    "Status" character varying(50) NOT NULL,
    "Priority" integer NOT NULL,
    "PriorityLabel" text NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "SenderName" text NOT NULL,
    "SenderId" text NOT NULL,
    "RecipientName" text NOT NULL,
    "RecipientId" text NOT NULL,
    "RiskScore" double precision NOT NULL,
    "OriginIp" text NOT NULL,
    "Device" text NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "FlagReasonsJson" text,
    "AssignedAnalystId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ReviewQueues" PRIMARY KEY ("Id")
);

CREATE TABLE "RuleThresholds" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RuleName" text NOT NULL,
    "ThresholdValue" numeric NOT NULL,
    "IsActive" boolean NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RuleThresholds" PRIMARY KEY ("Id")
);

CREATE TABLE "Transactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReferenceId" text NOT NULL,
    "SenderWalletId" integer NOT NULL,
    "ReceiverWalletId" integer,
    "Amount" numeric NOT NULL,
    "Status" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Note" text,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Wallets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Balance" numeric NOT NULL,
    "Currency" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Wallets" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260928103204_InitialPostgresSetup', '10.0.11');

COMMIT;

START TRANSACTION;
ALTER TABLE "Wallets" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;

ALTER TABLE "Users" ALTER COLUMN "UpdatedAt" TYPE timestamp without time zone;

ALTER TABLE "Users" ALTER COLUMN "DateOfBirth" TYPE timestamp without time zone;

ALTER TABLE "Users" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;

ALTER TABLE "Users" ADD "Status" text NOT NULL DEFAULT '';

ALTER TABLE "Transactions" ALTER COLUMN "Timestamp" TYPE timestamp without time zone;

ALTER TABLE "RuleThresholds" ALTER COLUMN "LastUpdated" TYPE timestamp without time zone;

ALTER TABLE "RuleAuditLogs" ALTER COLUMN "Timestamp" TYPE timestamp without time zone;

ALTER TABLE "ReviewQueues" ALTER COLUMN "UpdatedAt" TYPE timestamp without time zone;

ALTER TABLE "ReviewQueues" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;

ALTER TABLE "Notifications" ALTER COLUMN "Timestamp" TYPE timestamp without time zone;

ALTER TABLE "FraudFlags" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;

ALTER TABLE "DeviceSessions" ALTER COLUMN "LastLoginAt" TYPE timestamp without time zone;

ALTER TABLE "AuditLogs" ALTER COLUMN "Timestamp" TYPE timestamp without time zone;

ALTER TABLE "ApprovalDecisions" ALTER COLUMN "DecidedAt" TYPE timestamp without time zone;

ALTER TABLE "AgentExecutionLogs" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261005160134_FinalizeUtcFixes', '10.0.11');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261006021153_AddEmployeeIdToUsers', '10.0.11');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261006050501_AddNotificationCategory', '10.0.11');

COMMIT;

